name: provider_architecture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  responsive_screen: ^1.0.0
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  get_it: ^4.0.2
  http: ^0.12.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/
   
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
    - family: RobotoThin
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
          style: italic
